const $=s=>document.querySelector(s);
const percent=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?`${(Number(v)*100).toFixed(1)}%`:'尚未評測';
const seconds=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?`${Number(v).toFixed(2)} 秒`:'尚未評測';
function first(o,keys){for(const k of keys)if(o&&o[k]!==undefined&&o[k]!==null)return o[k];return null}
function metrics(target,rows){$(target).replaceChildren(...rows.map(([label,value])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);return row}))}
async function loadDashboard(){const r=await fetch('/admin/overview');if(!r.ok)throw new Error('無法載入成果總覽');const d=await r.json(),f=d.feedback,e=d.evaluations;$('#pendingCount').textContent=f.pending_count??0;$('#approvedReviewCount').textContent=f.approved_review_count??f.approved_count??0;$('#datasetApprovedCount').textContent=f.dataset_approved_count??f.approved_count??0;$('#consentedCount').textContent=f.consented_pending_count??0;
  const speech=e.speech?.summary||e.speech||{},rewrite=e.rewrite?.summary||e.rewrite||{},vision=e.vision?.summary||e.vision||{};
  const speechLatency=first(speech.latency_after_warmup,['average_inference_seconds'])??first(speech.latency_all_files,['average_inference_seconds'])??first(speech,['steady_state_mean_processing_seconds','average_inference_seconds','average_dual_pass_seconds','average_seconds']);
  metrics('#speechMetrics',[['平均 CER',percent(first(speech,['average_cer','baseline_average_cer','prompt_average_cer','routed_average_cer']))],['平均推論時間',seconds(speechLatency)],['測試案例',String(first(speech,['total_files','total_cases'])??'尚未評測')]]);
  metrics('#rewriteMetrics',[['自動通過率',percent(first(rewrite,['automatic_pass_rate']))],['LLM 採用率',percent(first(rewrite,['llm_candidate_accepted_rate']))],['穩態平均時間',seconds(first(rewrite,['steady_state_mean_processing_seconds','mean_processing_seconds']))]]);
  metrics('#visionMetrics',[['物件召回率',percent(first(vision,['object_recall']))],['OCR 召回率',percent(first(vision,['ocr_exact_text_recall']))],['需確認判斷正確率',percent(first(vision,['confirmation_accuracy']))]])}
async function loadServices(){const box=$('#serviceList');box.textContent='檢查中…';const r=await fetch('/admin/services'),d=await r.json();box.replaceChildren(...d.items.map(item=>{const row=document.createElement('div');row.className=`service ${item.status==='ok'?'ok':'warn'}`;const name=document.createElement('b'),status=document.createElement('span'),detail=document.createElement('small');name.textContent=item.name;status.textContent=item.status==='ok'?'可用':'需檢查';detail.textContent=item.detail||item.configured_model||'';row.append(name,status,detail);return row}))}
async function load(){const me=await fetch('/auth/me');if(!me.ok)return location.href='/app/login/';const data=await me.json();if(data.user.role!=='admin')return location.href='/app/';$('#adminName').textContent=data.user.display_name;try{await Promise.all([loadDashboard(),loadServices()])}catch(e){$('#dashboardError').textContent=e.message;$('#dashboardError').classList.remove('hidden')}const r=await fetch('/admin/users');if(r.ok){const users=(await r.json()).items;$('#userList').replaceChildren(...users.map(user=>{const row=document.createElement('div');row.className='user-row';row.innerHTML=`<b>${user.display_name}</b><span>${user.username}</span><span>${user.role==='admin'?'管理者':'一般使用者'}</span>`;return row}))}}
$('#serviceButton').onclick=loadServices;$('#logoutButton').onclick=async()=>{await fetch('/auth/logout',{method:'POST'});location.href='/app/login/'};$('#userForm').onsubmit=async e=>{e.preventDefault();const r=await fetch('/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:$('#newName').value,username:$('#newUsername').value,password:$('#newPassword').value,role:$('#newRole').value})}),d=await r.json();$('#userMessage').textContent=r.ok?'帳號已建立。':d.detail;if(r.ok){e.target.reset();load()}};load();
